In [2]:
import torch

In [3]:
# Создайте случайный FloatTensor размера 3x4x5

In [4]:
a = torch.randint(10, size=(3,4,5))
a

tensor([[[8, 5, 9, 7, 6],
         [7, 6, 0, 7, 4],
         [6, 6, 9, 4, 3],
         [4, 6, 8, 4, 2]],

        [[9, 9, 5, 3, 9],
         [2, 4, 1, 6, 3],
         [7, 7, 8, 1, 5],
         [6, 8, 5, 7, 5]],

        [[5, 5, 7, 0, 2],
         [2, 9, 8, 8, 0],
         [7, 5, 5, 2, 5],
         [3, 8, 6, 7, 1]]])

In [5]:
# Выведите его форму (shape)

In [6]:
a.shape

torch.Size([3, 4, 5])

In [7]:
# Приведите его к форме 6 X 10

In [8]:
a = a.reshape(6, 10)
a

tensor([[8, 5, 9, 7, 6, 7, 6, 0, 7, 4],
        [6, 6, 9, 4, 3, 4, 6, 8, 4, 2],
        [9, 9, 5, 3, 9, 2, 4, 1, 6, 3],
        [7, 7, 8, 1, 5, 6, 8, 5, 7, 5],
        [5, 5, 7, 0, 2, 2, 9, 8, 8, 0],
        [7, 5, 5, 2, 5, 3, 8, 6, 7, 1]])

In [9]:
# Умножьте его на вектор [1, 4, 2, 2, 1,5] поэлементно

In [25]:
b = [1, 4, 2, 2, 1,5]
b = torch.tensor(b)
b

tensor([1, 4, 2, 2, 1, 5])

In [31]:
a.T*b

tensor([[ 8, 24, 18, 14,  5, 35],
        [ 5, 24, 18, 14,  5, 25],
        [ 9, 36, 10, 16,  7, 25],
        [ 7, 16,  6,  2,  0, 10],
        [ 6, 12, 18, 10,  2, 25],
        [ 7, 16,  4, 12,  2, 15],
        [ 6, 24,  8, 16,  9, 40],
        [ 0, 32,  2, 10,  8, 30],
        [ 7, 16, 12, 14,  8, 35],
        [ 4,  8,  6, 10,  0,  5]])

In [26]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [37]:
a1 = torch.randint(10, size=(6,6))
a1

tensor([[6, 5, 9, 8, 1, 0],
        [9, 9, 9, 7, 1, 3],
        [3, 4, 3, 6, 8, 7],
        [1, 3, 9, 4, 5, 1],
        [3, 3, 2, 2, 6, 5],
        [5, 5, 0, 0, 7, 4]])

In [40]:
torch.matmul(a1, a1).size()

torch.Size([6, 6])

In [7]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [ ]:
# dy/dx = 3x**2
# dy/dz = 1
# dy/dt = -75

In [8]:
# Создайте единичный тензор размера 5x6

In [36]:
c = torch.ones((5, 6))
c

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [34]:
# Переведите его в формат numpy

In [42]:
c.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [29]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5

In [6]:
x = torch.ones((5, 6), requires_grad=True)
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], requires_grad=True)

In [7]:
x.grad

In [11]:
w1 = torch.randn((5,6), requires_grad=True)

In [13]:
z = x**w1 - 2 * x**2 + 5
z

tensor([[4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.]], grad_fn=<AddBackward0>)

In [14]:
z.backward(x)

In [15]:
x.grad

tensor([[-5.3824, -4.5146, -4.0482, -3.1449, -3.7215, -5.5175],
        [-4.9208, -3.4735, -5.0280, -2.7682, -5.5150, -2.2905],
        [-3.6149, -4.7616, -5.1641, -2.6611, -4.2181, -5.1951],
        [-4.0950, -4.3589, -4.3862, -3.2630, -3.9682, -4.5868],
        [-5.3914, -3.1593, -3.7818, -5.6178, -4.5608, -3.8578]])

In [16]:
x = torch.ones((5, 6))
w1 = torch.randn((5,6), requires_grad=True)
a = x**w1 - 2 * x**2 + 5 
sigma = torch.nn.functional.sigmoid(a)
mse = torch.nn.functional.mse_loss(sigma, x)
mse

/home/recpi/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py:1960: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


tensor(0.0003, grad_fn=<MseLossBackward0>)

In [17]:
mse.backward()

In [18]:
w1.grad

tensor([[-0., -0., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0., -0.]])

In [28]:
x = torch.ones((5, 6), requires_grad=True)
# a = torch.randn((3,3), requires_grad=True)

w1 = torch.randn((5,6), requires_grad=True)

a = x**w1 - 2 * x**2 + 5 

L = (10 - a).sum()


print("The grad fn for a is", x.grad_fn)
print("The grad fn for d is", a.grad_fn)
print(L)

L.backward()

The grad fn for a is None
The grad fn for d is <AddBackward0 object at 0x7fe18417f9d0>
tensor(180., grad_fn=<SumBackward0>)


In [26]:
x.is_leaf, w1.is_leaf

(True, True)

In [27]:
L.is_leaf

False